name: Full Tests

on:
  push:
    tags:
      # test release candidates
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'
  # can be triggered manually as well
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        resolution: ["highest"]
        include:
          - os: ubuntu-latest
            python-version: "3.10"
            resolution: "lowest-direct"
          - os: windows-latest
            python-version: "3.10"
            resolution: "lowest-direct"
          - os: macos-latest
            python-version: "3.10"
            resolution: "lowest-direct"

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Create virtual environment
        run: uv venv

      - name: Install brlib
        run: uv pip install --resolution ${{ matrix.resolution }} -e .[dev]

      - name: Run pytest
        run: uv run pytest
